spring:
  application:
    name: factory-product-service
  config:
    import: optional:configserver:http://localhost:8888
server:
  port: 10002

eureka:
  instance:
    instance-id: factory-product-service
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka

management:
  endpoints:
    web:
      exposure:
        include: "*"
